### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by WSLUser** [sgeto/libdnet#1]
I discovered a numerous amount of files missing from both this fork and the boundary fork that make it impossible to build from source. The literal files that allow ./configure such as the make files are completely gone. Not sure how you expect it to install from scratch without the necessary files. Please add the required files from the original source: code.google.com/p/libdnet and modify as needed to ensure it works as intended with your fixes (which is why i attempted to install from here in first place).

**Comment by sgeto** [comment]
The new school way of doing things is that those files are usually only included in a release.
When building from source control, you'll need to regenerate them yourself by running the [autogen.sh](https://github.com/sgeto/libdnet/blob/master/autogen.sh) script located in the repository's root directory. 
And before you do, make sure to have all Autotools and Libtool installed.

Good luck

**Comment by sgeto** [comment]
Or just run `autoreconf -i` once after cloning the repo

**Comment by sgeto** [comment]
You're welcome?
